// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABSQP-_m36VO13aNqQH5mHSoqZ1C1dylM',
    appId: '1:975277391882:web:ab39b9712ffb9e38f1dff3',
    messagingSenderId: '975277391882',
    projectId: 'chat-ionic-examen',
    authDomain: 'chat-ionic-examen.firebaseapp.com',
    databaseURL: 'https://chat-ionic-examen-default-rtdb.firebaseio.com',
    storageBucket: 'chat-ionic-examen.appspot.com',
    measurementId: 'G-GLLDDH7T5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAgtYas7jFhg_LanUGjxIkXNyOikTuXU8',
    appId: '1:975277391882:android:c12dc6e5fc2db349f1dff3',
    messagingSenderId: '975277391882',
    projectId: 'chat-ionic-examen',
    databaseURL: 'https://chat-ionic-examen-default-rtdb.firebaseio.com',
    storageBucket: 'chat-ionic-examen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB22szBewiTJNyJGQi3A28s77gtBMIuRFI',
    appId: '1:975277391882:ios:7ce6fa767a086cdff1dff3',
    messagingSenderId: '975277391882',
    projectId: 'chat-ionic-examen',
    databaseURL: 'https://chat-ionic-examen-default-rtdb.firebaseio.com',
    storageBucket: 'chat-ionic-examen.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB22szBewiTJNyJGQi3A28s77gtBMIuRFI',
    appId: '1:975277391882:ios:7ce6fa767a086cdff1dff3',
    messagingSenderId: '975277391882',
    projectId: 'chat-ionic-examen',
    databaseURL: 'https://chat-ionic-examen-default-rtdb.firebaseio.com',
    storageBucket: 'chat-ionic-examen.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
